### PR TITLE
Version v0.7.4

### PR DESCRIPTION
**Pull request by jpculp**
**Testing done:**

- Launched `aws-ecs-1` ami with new container set in userdata.
- Enabled the admin container via the control container's APIclient.
- Verified APIclient exec functionality.
- Verified Bottlerocket access via `sudo sheltie`.
- Connected to admin container via ec2 instance connect.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by jpculp** [comment]
Updated **CHANGELOG.md**.

**Review by zmrow — COMMENTED** [review]
Could you also test that SSH to the container works?  I didn't see that in the testing done.

**Review by etungsten — APPROVED** [review]

**Comment by jpculp** [comment]
My testing script tests SSH via ec2 instance connect, which generates a one-time-use SSH public key, pushes the key to the instance where it remains for 60 seconds, and connects the user to the instance.

That said, I just launched an instance using normal public key authentication powered by `shibaken` and it also worked.

**Review by zmrow — APPROVED** [review]
:hut:

**Pull request merged**
